const { summarize } = require('../parser/plan');

const ACTION_EMOJI = {
  create: '🟢',
  update: '🟡',
  delete: '🔴',
  replace: '🟣',
};

function truncate(str, len) {
  if (typeof str !== 'string') str = JSON.stringify(str) || '';
  if (str.length <= len) return str;
  return str.slice(0, len - 3) + '...';
}

function formatCost(cost) {
  if (cost === null || cost === undefined) return '';
  return `$${Number(cost).toFixed(2)}/mo`;
}

function renderMarkdown(resources, options = {}) {
  const lines = [];
  const summary = summarize(resources);
  const destructive = resources.filter(r => r.isDestructive);
  const totalMonthlyCost = resources.reduce((sum, r) => sum + (r.monthlyCost || 0), 0);

  lines.push('## Terraform Plan Summary');
  lines.push('');

  // Summary line
  const parts = [];
  if (summary.create > 0) parts.push(`**+${summary.create}** to create`);
  if (summary.update > 0) parts.push(`**~${summary.update}** to update`);
  if (summary.replace > 0) parts.push(`**±${summary.replace}** to replace`);
  if (summary.delete > 0) parts.push(`**-${summary.delete}** to destroy`);
  lines.push(parts.join(' · ') + ` (${summary.total} total)`);
  lines.push('');

  // Destructive warning
  if (destructive.length > 0) {
    lines.push('> [!CAUTION]');
    lines.push('> **Destructive changes detected:**');
    for (const r of destructive) {
      lines.push(`> - ${ACTION_EMOJI[r.action]} \`${r.address}\` will be **${r.actionLabel}d**`);
    }
    lines.push('');
  }

  // Cost
  const hasUsageBased = resources.some(r => r.costType === 'usage-based');
  if (totalMonthlyCost > 0) {
    lines.push(`**Estimated fixed monthly cost: $${totalMonthlyCost.toFixed(2)}/mo**`);
    if (hasUsageBased) {
      lines.push('');
      lines.push('> *Usage-based resources (S3, SQS, Lambda, etc.) depend on actual consumption*');
    }
    lines.push('');
  }

  // Resource table
  if (!options.summaryOnly) {
    lines.push('| Action | Resource | Cost |');
    lines.push('|--------|----------|------|');

    for (const r of resources) {
      const emoji = ACTION_EMOJI[r.action] || '⚪';
      let costStr = '';
      if (r.monthlyCost !== null) {
        costStr = formatCost(r.monthlyCost);
      } else if (r.costType === 'usage-based') {
        costStr = '_usage-based_';
      } else if (r.costType === 'free') {
        costStr = '-';
      }

      lines.push(`| ${emoji} ${r.actionLabel} | \`${r.address}\` | ${costStr} |`);
    }
    lines.push('');

    // Field diffs as details blocks
    const updatesWithDiffs = resources.filter(r => r.diffs && r.diffs.length > 0);
    if (updatesWithDiffs.length > 0) {
      lines.push('<details>');
      lines.push('<summary>Field-level changes</summary>');
      lines.push('');

      for (const r of updatesWithDiffs) {
        lines.push(`#### \`${r.address}\``);
        lines.push('```diff');
        for (const diff of r.diffs) {
          const fromStr = truncate(diff.from, 60);
          const toStr = truncate(diff.to, 60);
          switch (diff.type) {
            case 'add':
              lines.push(`+ ${diff.field} = ${toStr}`);
              break;
            case 'remove':
              lines.push(`- ${diff.field} = ${fromStr}`);
              break;
            case 'change':
              lines.push(`- ${diff.field} = ${fromStr}`);
              lines.push(`+ ${diff.field} = ${toStr}`);
              break;
          }
        }
        lines.push('```');
        lines.push('');
      }

      lines.push('</details>');
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('*Generated by [tfsummary](https://github.com/rohnnair/tfsummary)*');
  lines.push('');

  return lines.join('\n');
}

module.exports = { renderMarkdown };
